language: python

#
# Test test matrix is spelled out explicitly here.
#
# For each supported version of Python, we will test with coverage.
#
matrix:
  include:
  - python: 3.6
    env: TOXENV=pep8

  - python: 2.6
    env: TOXENV=py26,codecov
  - python: 2.7
    env: TOXENV=py27,codecov
  - python: 3.4
    env: TOXENV=py34,codecov
  - python: 3.5
    env: TOXENV=py35,codecov
  - python: 3.6
    env: TOXENV=py36,codecov

  # Failures on these unsupported python versions are allowed
  allow_failures:
  - env: TOXENV=pep8

install:
- pip install tox

script:
- tox -vvv
